### ISSUE TITLE
RTX-KG2 appearing twice

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/kp-registry#27]
In prod kp-registry, there are entries for both prod and dev RTX-KG2.  I checked the smartapi registrations, and both make use of the infores tag with the same value.  So kp-registry should be using only the prod version.

**Comment by maximusunc** [comment]
This was by design. The kp-registry will store both maturities, and then it is up to the service requesting kps to specify which maturity level it wants. (Could be a list of maturities in priority order and the best one will be returned).

**Comment by cbizon** [comment]
Oh, I get it.   Thanks for clarifying.
