### ISSUE TITLE
Not picking up ontology-kp

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/kp-registry#33]
This is the registration: https://smart-api.info/api/metadata/2ca2daadd989387f1e8f7121fa214eda

But I don't see it in the list of KPs after we refresh.   It's probably an error in the registration if I had to make a guess.

**Comment by kennethmorton** [comment]
Their servers block is missing "x-maturity" and we are filtering it out.

**Comment by kennethmorton** [comment]
The servers block with x-maturity looks good. However something else has gone wrong. The registration shows up as failing in the smart-api registry.
